# Generated by Django 5.2.4 on 2025-11-01 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_likes_post_liked_by_post_readed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='readed_by',
            new_name='read_by',
        ),
    ]
