# Generated by Django 6.0.1 on 2026-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reply', 'Someone replied to your post'), ('like', 'Someone liked your post'), ('follow', 'Someone has followed you'), ('mention', 'Someone mentioned you'), ('followed_user_posted', 'Someone you follow created a post'), ('system', 'System notification'), ('other', 'Other')])),
            ],
        ),
    ]
