# Generated by Django 5.2.4 on 2025-11-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_event_unique_actor_per_notification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_actor_per_notification',
        ),
    ]
