# Generated by Django 5.2.4 on 2025-11-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_copy_bot_personality_to_personality_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='personality',
        ),
    ]
