# Generated by Django 5.2.4 on 2025-12-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_remove_bot_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='mode',
            field=models.CharField(choices=[('active', 'Active'), ('sleeping', 'Sleeping'), ('inactive', 'Inactive')], default='active'),
        ),
    ]
