# Generated by Django 5.2.4 on 2025-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_bot_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='mode',
            field=models.CharField(choices=[('active', 'Active'), ('standby', 'Standby'), ('inactive', 'Inactive')], default='active'),
        ),
    ]
