# Generated by Django 6.0.5 on 2026-05-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0004_post_embeddings_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_embeddings', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('replies_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(db_index=True, default=0)),
                ('is_hot', models.BooleanField(db_index=True, default=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='posts.post')),
            ],
        ),
    ]
