# Generated by Django 6.0.5 on 2026-05-20 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_replies_count_alter_post_published_at'),
        ('recommendations', '0002_postmetrics_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmetrics',
            name='id',
        ),
        migrations.AlterField(
            model_name='postmetrics',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='posts.post'),
        ),
    ]
