# Generated by Django 6.0.4 on 2026-05-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_dislikes_count_post_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embeddings_created',
            field=models.BooleanField(default=False),
        ),
    ]
