# Generated by Django 6.0.5 on 2026-05-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_embeddings_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='replies_count',
        ),
    ]
