# Generated by Django 6.0.5 on 2026-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_replies_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
