# Generated by Django 5.2.4 on 2025-11-10 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_created_at_and_more'),
        ('posts', '0007_post_mentioned_users_alter_post_read_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_user',
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('notification_type', 'recipient', 'related_post'), name='unique_notification_group'),
        ),
    ]
