# Generated by Django 5.2.4 on 2025-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
