# Generated by Django 5.2.4 on 2025-08-10 15:56

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_likes_post_liked_by_post_readed_by'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_in_model', models.BooleanField(default=False)),
                ('embedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.postembedding')),
            ],
        ),
        migrations.DeleteModel(
            name='InteractionEmbedding',
        ),
    ]
